apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: node-redis-example-3
    component: webservice
  name: webservice
spec:
  replicas: 2
  selector:
    matchLabels:
      application: node-redis-example-3
      component: webservice
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        application: node-redis-example-3
        component: webservice
        redeploy: '1'
    spec:
      containers:
        - name: webservice
          image: webservice:1.0.0
          env:
          - name: REDIS_SERVER_IP
            value: "redis-server"
          ports:
          - name: webservice
            containerPort: 3000
            protocol: TCP