apiVersion: v1
kind: Service
metadata:
  name: webservice
  labels:
    application: node-redis-example-3
    component: webservice
spec:
  type: NodePort
  selector:
    application: node-redis-example-3
    component: webservice
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000